spring.application.name=cliente

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/clientedb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port app
server.port=8080

# Logging
# Nivel geral da aplicacao
logging.level.root=WARN

# Nivel especificodo pacote - mostrar todos os logs da app
logging.level.com.projeto.cliente=DEBUG

# Nivel do Hibernate - mostrar as consultas SQL
logging.level.org.hibernate.SQL=DEBUG

# salar logs em arquivo
logging.file.nema=logs/cliente-api.log

# formato do log no console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# formato do log no arquivo
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
